---
- name: Install docker & docker-compose
  dnf:
    name: "{{ docker_packages }}"
    state: present
  vars:
    docker_packages:
      - docker
      - docker-compose

- name: Ensure existence of docker group
  group:
    name: 'docker'
    state: present

- name: Add user to docker group
  user:
    name: "{{ user }}"
    append: yes
    groups: 'docker'
    state: present

- name: Enable/start docker service
  service:
    name: docker
    state: started
    enabled: yes
