---
- name: Setup bastion host
  become: True
  hosts: bastion
  roles:
    - role: install-packages
    - role: setup-docker
      when: setup_docker == True
    - role: setup-monitoring
      when: setup_monitoring == True
